Exercise_2/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Services.Models.Cart;
using Services.Repository;
using Services.Services;
using System;
using System.Configuration;

public class ModelProduct
{
	public int cartId { get; set; }
	public int productId { get; set; }
	public int quantity { get; set; }
}
public class CartUpdate
{
    public int CartId { get; set; }
    public int ProductId { get; set; }
    public int Quantity { get; set; }
}

namespace WebApplication1.Controllers
{


	[Route("/cart")]
	public class CartController : Controller
	{
		private CartService _cartService;
		private CustomerService _cutomerService;

		public CartController(MyDbContext db)
		{
			_cartService = new CartService(db);
			_cutomerService = new CustomerService(db);
		}

		[HttpGet]
		public IActionResult Index()
		{
			var cusID = HttpContext.Session.GetString("customerID");
			var cartId = HttpContext.Session.GetString("cartId");



			if (cusID == null && cartId == null)
			{
				ViewBag.Message = "Please login to use cart feature!";
				return View();
			}
			else
			{
				int.TryParse(cartId, out int cartIdInt);
				var cart = _cartService.GetCartById(cartIdInt);
				var cartDetails = _cartService.GetCartDetails(cartIdInt);

				decimal sum = cartDetails.Sum((cd) => cd.Product.Price * cd.Quantity);

				ViewBag.ListProduct = cartDetails;
				ViewBag.CartId = cart.Id;
				ViewBag.Total = sum;
				return View();

			}

		}

		[HttpGet("{id}")]
		public IActionResult Index(int id)
		{
			var cusID = HttpContext.Session.GetString("customerID");
			if (cusID == null)
			{
				ViewBag.Message = "Please login to use cart feature!";
				return View();
			}
			else
			{
				ViewData["username"] = HttpContext.Session.GetString("username");
				ViewData["Name"] = HttpContext.Session.GetString("Name");

				var cart = _cartService.GetCartById(id);
				var cartDetails = _cartService.GetCartDetails(id);

				decimal sum = cartDetails.Sum((cd) => cd.Product.Price * cd.Quantity);

				ViewBag.ListProduct = cartDetails;
				ViewBag.Cart = cart;
				ViewBag.Total = sum;
				return View();
			}
		}

		[HttpPost]
		public IActionResult Index([FromForm] ModelProduct model)
		{
			var cusID = HttpContext.Session.GetString("customerID");

			if (model == null) return BadRequest("null");

			if (cusID == null)
			{
				ViewBag.Message = "Please login to use cart feature!";
				return View();
			}
			else
			{
				var cart = _cartService.GetCartById(model.cartId);

				var cartDetails = _cartService.GetCartDetails(model.cartId);

				var existing = cartDetails.FirstOrDefault(c => c.Product.Id == model.productId);

				if (existing != null)
				{
					_cartService.UpdateCartItem(model.cartId, model.productId, model.quantity + existing.Quantity);
				}
				else
				{
					_cartService.AddToCart(model.cartId, model.productId);
				}

				cartDetails = _cartService.GetCartDetails(model.cartId);

				decimal sum = cartDetails.Sum((cd) => cd.Product.Price * cd.Quantity);

				ViewBag.ListProduct = cartDetails;
				ViewBag.Cart = cart;
				ViewBag.Total = sum;

				return RedirectToAction("Index");
			}
		}

		[HttpGet("delete")]
		public IActionResult Delete([FromQuery] int cartId, [FromQuery] int productId)
		{
			_cartService.RemoveFromCart(cartId, productId);
			return RedirectToAction("Index");
		}

		[HttpPut("update")]
		public IActionResult UpdateCart([FromForm] CartUpdate cartUpdate)
		{
			try
			{
				_cartService.UpdateCartItem(cartUpdate.CartId, cartUpdate.ProductId, cartUpdate.Quantity);
				var response = new
				{
					Code = 0,
					Message = "Cart item updated successfully"
				};
				return new JsonResult(response);
			}
			catch (Exception ex)
			{
				var response = new
				{
					Code = 1,
					Message = $"Failed to update the cart item. Detail: {ex.Message}"
				};
				return new JsonResult(response);
			}
		}
	}
}

Exercise_2/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Models.Cart;
using Services.Models.Customers;
using Services.Models.Order;
using Services.Repository;
using Services.Services;
using System;
using System.Text.Json;

namespace WebApplication1.Controllers
{
	[Route("/order")]
	public class OrderController : Controller
	{
		private string _orderId;
		private CartService _cartService;
		private OrderService _orderService;
		private CustomerService _customerService;
		public OrderController(MyDbContext db)
		{
            _orderService = new OrderService(db);
			_cartService = new CartService(db);
            _customerService = new CustomerService(db);
        }

		[HttpGet]
		public IActionResult AllOrder()
		{
			var cusId = HttpContext.Session.GetString("CustomerPhone");
			if (cusId != null)
				ViewBag.Orders = _orderService.GetAllOrder(cusId);
			return View("Index");
		}

		[HttpGet("payment")]
		public IActionResult GetPayment([FromQuery] decimal total, [FromQuery] int cartId)
		{
			var cusId = HttpContext.Session.GetString("CustomerId");

			ViewBag.Total = total;
			ViewBag.CartId = cartId;	
			ViewBag.CustomerId = cusId;
			ViewBag.ListProduct = _cartService.GetCartDetails(cartId);

			return View();
		}

		[HttpPost("payment")]
		public IActionResult SubmitPayment([FromForm]int cartId,[FromForm]decimal total, [FromForm]string info, [FromForm]string bankcode="VNPAYQR")
		{
			var customerPhone = HttpContext.Session.GetString("customerID");

            if (customerPhone == null)
			{
				return RedirectToAction("Failed");
			}

			var orderRefId = Guid.NewGuid().ToString().Replace("-","");

			Order order = new Order() { 
				ReferenceId = orderRefId,
				Status = false,
				TotalAmount = total,
				OrderDate = DateTime.Now,
				Customer = _customerService.GetCustomerByPhone(customerPhone)
            };
			
			var vnp_url = VNPayService.GeneratePaymentUrl(total, bankcode, info, orderRefId);

			_orderService.CreateOrder(order);
			return Redirect(vnp_url);
		}

		[HttpGet("callback")]
		public IActionResult CallBack()
		{
			var Request = HttpContext.Request;

            string? vnpResponseCode = Request.Query["vnp_ResponseCode"];
            string? vnp_TxnRef = Request.Query["vnp_TxnRef"];

            if (vnpResponseCode == "00" && !string.IsNullOrEmpty(vnp_TxnRef))
            {

				_orderService.UpdateOrder(vnp_TxnRef);
				TempData["Message"] = $"Order success";
				TempData["Date"] = DateTime.Now.ToString();
                TempData["orderID"] = vnp_TxnRef;
                return RedirectToAction("Success");
            }
            else
            {
                return RedirectToAction("Failed");
            }
        }

		[HttpGet("success")]
		public IActionResult Succes() {
			return View(); 
		}
		
		[HttpGet("failed")]
        public IActionResult Failed() {
            return View(); 
		}
	}
}

Exercise_2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style>
        a {
            text-decoration: none;
            color: black;
        }

        .icon{
            font-size: 16px;
            padding: 5px;
            margin-right:10px
        }

        .fit-content-with-padding {
            line-height: 24px;
            width: fit-content;
            height: fit-content;
            padding: 5px;
        }

        a:active {
            color: black;
        }

        body {
            margin: 0;
        }

        li > a:hover {
            text-decoration: underline;
            color: red;
        }

        ul {
            list-style: none;
            padding: 0;
        }

        li {
            display: flex;
        }

        img {
            max-width: 100%;
        }

        .footer-content .list-info p {
            font-size: 14px;
        }

        .footer-title h4 {
            font-size: 16px;
        }

        .list-ship li, .list-pay li {
            width: calc(100%/4);
            display: inline-flex;
            padding: 2px;
            color: black;
        }

        .button {
            margin: 0 5px;
        }

        .input-number {
            width: 40px;
            margin-right: 5px;
            border: none;
            text-align: center;
        }

        th > td {
            text-align: left;
            padding: 0;
        }

        table {
            text-align: left;
        }

    </style>
</head>
<body>

    <header class="p-3 bg-white ">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 font-weight-bold text-decoration-none" style="font-size:32px">
                    DotnetShop
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="#" class="nav-link px-2 text-secondary"></a></li>
                    <li><a href="#" class="nav-link px-2 text-white"></a></li>
                    <li><a href="#" class="nav-link px-2 text-white"></a></li>
                    <li><a href="#" class="nav-link px-2 text-white"></a></li>
                    <li><a href="#" class="nav-link px-2 text-white"></a></li>
                </ul>

                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                    <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
                </form>
                @{
                    if (ViewData["Name"] != null)
                    {
                        <div class="text-end" style="display: flex; align-items: center; justify-content: center;">
                            <a asp-controller="Cart" asp-action="Index" class="text-decoration-none text-black" style="margin-right: 5px; border:1px solid black; border-radius:4px; padding: 3px 12px">Cart</a>
                        </div>
                        <div class="dropdown">
                            <button class="mx-2 btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                 Welcome, @ViewData["Name"]
                            </button>
                            <div class="dropdown-menu">
                              <a class="dropdown-item" asp-controller="Order" asp-action="AllOrder">Orders</a>
                              <a class="dropdown-item" href="/login/logout">Log out</a>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="text-end" >
                            <a asp-controller="Login" asp-action="Index" class="text-decoration-none btn">Login</a>
                            <a href="/Login/Register" class="text-decoration-none text-black btn">Register</a>
                        </div>
                    }
                }
            </div>
        </div>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    <script>
        $(document).ready(function () {

            $("#priceRange").on("change", function () {
                let selectedCategory = $("input[name='category']:checked").val();
                let selectedSort = "asc";

                let minPrice = 0;
                let maxPrice = $("#priceRange").val() > 0 ? $("#priceRange").val() + "00000" : null;
                let page = $(this).data("page") || 1;

                console.log({ category: selectedCategory, sort: selectedSort, minPrice: minPrice, maxPrice: maxPrice });

                $.ajax({
                    type: "GET",
                    url: "/filter",
                    data: { category: selectedCategory, sort: selectedSort, minPrice: minPrice, maxPrice: maxPrice, page: page },
                    success: function (data) {
                        $("#productListings").html(data);
                    }
                });
            });

            // Xử lý sự kiện khi người dùng chọn category, sort, hoặc trang
            $(".category-option, #sortDesc, #sortAsc, .pagination a").on("click", function (event) {
                event.preventDefault();

                $(".form-check-input.category-option.active").removeClass("active");
                $(this).addClass("active");

                var selectedCategory = $(".category-option.active").data("id");

                var selectedSort = $(this).data("value");

                var minPrice = 0;
                var maxPrice = $("#priceRange").val() > 0 ? $("#priceRange").val()+"00000" : null;
                var page = $(this).data("page") || 1;

                console.log({ category: selectedCategory, sort: selectedSort, minPrice: minPrice, maxPrice: maxPrice });

                $.ajax({
                    type: "GET",
                    url: "/filter",
                    data: { category: selectedCategory, sort: selectedSort, minPrice: minPrice, maxPrice: maxPrice, page: page },
                    success: function (data) {
                        $("#productListings").html(data);
                    }
                });
            });
        });

    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>